/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
export const domain={
 code:'SBOM',systemName:'知华 SBOM',englishName:'SOFTWARE SUPPLY CHAIN CONTROL',theme:{primary:'#6656a5',dark:'#2c3044',accent:'#2d91a1'},workspace:'研发效能中心 / 软件供应链治理',fieldWorkspace:'应用供应链组',period:'2026-08-02 · 发布窗口',liveText:'组件情报于 10:39 更新',fieldContextLabel:'当前产品线',fieldContext:'企业应用 · Release 4.8',fieldUser:'陆遥',fieldRole:'组件治理工程师',adminUser:'何谨',adminRole:'开源治理负责人',adminTitle:'软件物料清单与供应链风险中心',adminBreadcrumb:'SBOM / 供应链态势',adminSubtitle:'持续盘点产品组件、漏洞、许可证、来源和构建证明，为发布提供可追溯门禁。',exportAction:'导出 CycloneDX',createAction:'创建扫描任务',chartTitle:'高风险组件处置趋势',chartSubtitle:'累计处置率 / 发布门禁目标',chartLabels:['01日','05日','09日','13日','17日','21日','25日','29日','31日'],loadTitle:'产品线治理负荷',loadSubtitle:'开放风险占团队处理能力',recordsTitle:'重点组件治理任务',recordsSubtitle:'按漏洞可利用性、许可证策略和发布时间排序',issueTitle:'供应链发布风险',issueSubtitle:'需要安全、研发或法务协调的事项',recordName:'治理任务',itemName:'产品版本',unitName:'责任团队',batchName:'发布版本',planName:'组件',doneName:'已处置',exceptionName:'策略命中',unitLabel:'个',
 listBreadcrumb:'供应链治理 / 任务中心',listSubtitle:'管理 SBOM 生成、组件归一、漏洞匹配、许可证审核、整改和发布证明。',listSummary:[['在管产品','36'],['组件版本','12.8K'],['高危漏洞','18'],['发布阻断','3',true]],tabs:['全部','待扫描','处置中','待复核','已归档'],fieldBreadcrumb:'SBOM / 组件工程师工作台',fieldTitle:'软件供应链治理工作台',fieldSubtitle:'当前 6 个治理任务 · 3 个发布阻断 · 工程师陆遥',fieldSecondary:'查看发布日历',reportAction:'提交处置结果',fieldNoticeTitle:'漏洞与许可证情报同步正常',fieldNotice:'过去 24 小时已匹配 12,846 个组件版本，来源覆盖率 98.1%',steps:['生成 SBOM','组件归一','风险匹配','整改复核','发布归档'],documentAction:'查看治理规范',printAction:'导出证明包',resourceCardTitle:'扫描与情报能力',resourceValueLabel:'组件版本',resourceHealthLabel:'来源覆盖率',quickSubtitle:'组件工程师常用入口',quickActions:[['处置反馈','/shopfloor/report','升级、缓解与证明材料'],['组件检索','/shopfloor/material','名称、版本、哈希与许可证'],['扫描设施','/shopfloor/resources','SCA、固件识别与情报源'],['发布升级','/shopfloor/andon','严重漏洞和许可证阻断']],reportDefaults:[6,1],reportTitle:'组件风险处置反馈',reportSubtitle:'记录已处置组件、残余风险和证明材料。',reportSuccess:'处置结果已写入产品 SBOM 历史',reportPlaceholder:'填写升级版本、缓解措施、验证结果和证明地址',reportFootnote:'提交后触发产品 SBOM 重建与策略复核',ruleTitle:'软件供应链发布门禁',ruleSubtitle:'SBOM-POLICY · V2.3',rules:[['SBOM 格式','CycloneDX 1.6'],['严重漏洞','24 小时'],['禁止许可证','不得发布'],['构建证明','必须归档',true]],fieldTotals:[['36','在管产品'],['12.8K','组件版本'],['18','高危漏洞'],['98.1%','来源覆盖率']],
 adminMenus:[['/admin','home','供应链控制中心'],['/admin/work-orders','order','治理任务'],['/admin/samples','box','产品 SBOM'],['/admin/schedule','calendar','发布日历'],['/admin/methods','process','风险策略'],['/admin/reviews','quality','发布复核'],['/admin/resources','machine','扫描与情报'],['/admin/report','chart','风险分析']],fieldMenus:[['/shopfloor','home','工程师工作台'],['/shopfloor/report','report','处置反馈'],['/shopfloor/tasks','order','我的任务'],['/shopfloor/material','box','组件检索'],['/shopfloor/resources','machine','扫描设施'],['/shopfloor/andon','risk','发布升级',3]],moduleTitles:{tasks:['我的治理任务','查看产品版本、风险数量与发布期限'],material:['组件检索','按 PURL、版本、哈希、许可证和来源查询'],resources:['扫描与情报设施','查看 SCA、固件识别、漏洞源和策略引擎'],andon:['发布风险升级','提交严重漏洞或许可证阻断处置'],samples:['产品 SBOM','查看产品、组件、依赖关系和生成历史'],schedule:['发布日历','协调扫描、整改、复核和发布窗口'],methods:['风险策略','维护 CVSS、利用情报、许可证和 SLA 规则'],reviews:['发布复核','验证整改、SBOM、签名和构建证明'],report:['风险分析','分析组件暴露、修复时效和许可证趋势']},tagline:'知道软件里有什么，才能对供应链风险负责',storyTitle:'从每一个组件出发，<br/>建立可追溯的发布信任。',storyText:'面向研发、产品安全和开源合规团队的软件物料清单与供应链治理平台。',pattern:[2,5,7,10,13,16,19,22,25,28,30,32],loginStats:[['12.8K','组件版本'],['18','高危漏洞'],['98.1%','来源覆盖率']],loginTitle:'软件物料清单与供应链风险中心',adminDemo:'产品 / 漏洞 / 许可',fieldDemo:'扫描 / 处置 / 证明'
}
export const records=[{no:'SBOM-260801-018',name:'支付服务高危组件修复',code:'PAYMENT-API',unit:'应用供应链组',group:'研发效能中心',plan:24,done:16,exception:3,due:'08-03',batch:'Release 4.8.2',status:'处置中',progress:67,priority:'加急'},{no:'SBOM-260801-021',name:'边缘网关固件组件盘点',code:'EDGE-GATEWAY',unit:'设备软件组',group:'产品工程中心',plan:18,done:8,exception:1,due:'08-04',batch:'Firmware 12.6',status:'扫描中',progress:48,priority:'关注'},{no:'SBOM-260802-006',name:'数据控制台许可证复核',code:'DATA-CONSOLE',unit:'开源合规组',group:'法务与合规部',plan:12,done:0,exception:0,due:'08-06',batch:'Release 3.2',status:'待复核',progress:12,priority:'加急'},{no:'SBOM-260728-015',name:'移动客户端发布物证明归档',code:'MOBILE-CLIENT',unit:'应用供应链组',group:'研发效能中心',plan:20,done:20,exception:1,due:'08-01',batch:'iOS 8.9',status:'已归档',progress:100,priority:'正常'},{no:'SBOM-260802-009',name:'数据处理平台传递依赖升级',code:'DATA-PIPELINE',unit:'应用供应链组',group:'研发效能中心',plan:16,done:11,exception:2,due:'08-05',batch:'Release 6.1',status:'待验证',progress:73,priority:'关注'}]
export const resources=[{code:'SCAN-SCA-03',name:'应用依赖扫描器',unit:'研发效能中心',status:'在线',health:98,value:'9.6K',valueUnit:'组件',note:'覆盖 124 个代码仓库'},{code:'SCAN-FW-02',name:'固件组件识别器',unit:'产品工程中心',status:'在线',health:91,value:'2.1K',valueUnit:'组件',note:'覆盖 18 个设备版本'},{code:'FEED-VULN-08',name:'漏洞与利用情报源',unit:'研发效能中心',status:'预警',health:77,value:'12m',valueUnit:'延迟',note:'一条上游情报源同步延迟'}]
export const reviews=[{no:'REL-260801-032',title:'支付服务严重漏洞发布复核',type:'发布门禁',detail:'6 个修复组件 · 何谨',result:'待确认'},{no:'REL-260801-011',title:'边缘网关组件来源核验',type:'来源证明',detail:'18 个包 · 陆遥',result:'通过'},{no:'REL-260728-018',title:'数据控制台许可证兼容性',type:'开源合规',detail:'命中 AGPL-3.0',result:'异常'}]
export const adminMetrics=[['在管产品','36','覆盖 9 条产品线','blue'],['组件版本','12.8K','来源覆盖率 98.1%','green'],['高危漏洞','18','7 个存在已知利用','orange'],['发布阻断','3','含 1 个许可证风险','red']]
export const fieldMetrics=[['我的治理任务','6','3 个临近发布','blue'],['今日已处置','34','组件升级与缓解','green'],['待复核风险','12','5 项 SLA 临近','orange'],['来源覆盖率','98.1%','目标 99%','slate']]
export const chartActual=[11,19,28,37,48,59,68,77,84],chartTarget=[15,25,35,45,55,65,75,85,95]
export const loads=[['企业应用产品线',86,'开放风险 32 个'],['设备与固件产品线',78,'开放风险 21 个'],['数据平台产品线',69,'开放风险 18 个'],['移动客户端产品线',54,'开放风险 11 个']]
export const issues=[{type:'漏洞',title:'支付服务组件存在已知利用漏洞',detail:'CVSS 9.8 · 修复版本可用',status:'阻断'},{type:'许可',title:'数据控制台引入未批准 AGPL 组件',detail:'影响 Release 3.2 发布',status:'法务复核'},{type:'来源',title:'边缘网关 12 个二进制包来源未知',detail:'需要供应商补充构建证明',status:'处理中'}]
